Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Controllers/DeudaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuentasPorPagar.Models;

namespace CuentasPorPagar.Controllers
{
    public class DeudaController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Deuda/

        public ActionResult Index()
        {
            var deudas = db.Deudas.Include(d => d.Documento).Include(d => d.Proveedor);
            return View(deudas.ToList());
        }

        //
        // GET: /Deuda/Details/5

        public ActionResult Details(int id = 0)
        {
            Deuda deuda = db.Deudas.Find(id);
            if (deuda == null)
            {
                return HttpNotFound();
            }
            return View(deuda);
        }

        //
        // GET: /Deuda/Create

        public ActionResult Create()
        {
            ViewBag.tipoDocs = new SelectList(db.tipoDocumentoes, "idTipoDocumento", "nombre");
            ViewBag.idProveedor = new SelectList(db.Proveedors, "idProveedor", "Nombre");      
            Deuda deuda=new Deuda();
            Documento doc = new Documento();       
            deuda.Documento=doc;
            deuda.fechaInicio = DateTime.Now;
            deuda.fechaFin = DateTime.Now;
            return View(deuda);
        }

        //
        // POST: /Deuda/Create

        [HttpPost]
        public ActionResult Create(Deuda deuda)
        {
            if (ModelState.IsValid)
            {
                
                string physicalPath = HttpContext.Server.MapPath("../") + "UploadImages" + "\\";

                for (int i = 0; i < Request.Files.Count; i++)
                {
                    String urlDoc = physicalPath + System.IO.Path.GetFileName(Request.Files[i].FileName);
                    Request.Files[0].SaveAs(urlDoc);
                    deuda.Documento.URL = urlDoc;
                }
                tipoDocumento tipoDoc = db.tipoDocumentoes.Find(deuda.Documento.idTipoDocumento);
                deuda.Documento.tipoDocumento = tipoDoc;
                db.Documentoes.Add(deuda.Documento);
                deuda.Documento.URL = "url";
                db.SaveChanges();
                db.Deudas.Add(deuda);
                db.SaveChanges();

                return RedirectToAction("Index","Home");
            }

            ViewBag.idDocumento = new SelectList(db.Documentoes, "idDocumento", "URL", deuda.idDocumento);
            ViewBag.idProveedor = new SelectList(db.Proveedors, "idProveedor", "Direccion", deuda.idProveedor);
            return View(deuda);
        }

        //
        // GET: /Deuda/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Deuda deuda = db.Deudas.Find(id);
            if (deuda == null)
            {
                return HttpNotFound();
            }
            ViewBag.idDocumento = new SelectList(db.Documentoes, "idDocumento", "URL", deuda.idDocumento);
            ViewBag.idProveedor = new SelectList(db.Proveedors, "idProveedor", "Direccion", deuda.idProveedor);
            return View(deuda);
        }

        //
        // POST: /Deuda/Edit/5

        [HttpPost]
        public ActionResult Edit(Deuda deuda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deuda).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idDocumento = new SelectList(db.Documentoes, "idDocumento", "URL", deuda.idDocumento);
            ViewBag.idProveedor = new SelectList(db.Proveedors, "idProveedor", "Direccion", deuda.idProveedor);
            return View(deuda);
        }

        //
        // GET: /Deuda/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Deuda deuda = db.Deudas.Find(id);
            if (deuda == null)
            {
                return HttpNotFound();
            }
            return View(deuda);
        }

        //
        // POST: /Deuda/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Deuda deuda = db.Deudas.Find(id);
            db.Deudas.Remove(deuda);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Controllers/FormaPagoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuentasPorPagar.Models;

namespace CuentasPorPagar.Controllers
{
    public class FormaPagoController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /FormaPago/

        public ActionResult Index()
        {
            return View(db.FormaDePagoes.ToList());
        }

        //
        // GET: /FormaPago/Details/5

        public ActionResult Details(int id = 0)
        {
            FormaDePago formadepago = db.FormaDePagoes.Find(id);
            if (formadepago == null)
            {
                return HttpNotFound();
            }
            return View(formadepago);
        }

        //
        // GET: /FormaPago/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /FormaPago/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormaDePago formadepago)
        {
            if (ModelState.IsValid)
            {
                db.FormaDePagoes.Add(formadepago);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(formadepago);
        }

        //
        // GET: /FormaPago/Edit/5

        public ActionResult Edit(int id = 0)
        {
            FormaDePago formadepago = db.FormaDePagoes.Find(id);
            if (formadepago == null)
            {
                return HttpNotFound();
            }
            return View(formadepago);
        }

        //
        // POST: /FormaPago/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormaDePago formadepago)
        {
            if (ModelState.IsValid)
            {
                db.Entry(formadepago).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(formadepago);
        }

        //
        // GET: /FormaPago/Delete/5

        public ActionResult Delete(int id = 0)
        {
            FormaDePago formadepago = db.FormaDePagoes.Find(id);
            if (formadepago == null)
            {
                return HttpNotFound();
            }
            return View(formadepago);
        }

        //
        // POST: /FormaPago/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FormaDePago formadepago = db.FormaDePagoes.Find(id);
            db.FormaDePagoes.Remove(formadepago);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Controllers/PagoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuentasPorPagar.Models;

namespace CuentasPorPagar.Controllers
{
    public class PagoController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /Pago/

        public ActionResult Index()
        {
            var pagoes = db.Pagoes.Include(p => p.FormaDePago);
            return View(pagoes.ToList());
        }

        //
        // GET: /Pago/Details/5

        public ActionResult Details(int id = 0)
        {
            Pago pago = db.Pagoes.Find(id);
            if (pago == null)
            {
                return HttpNotFound();
            }
            return View(pago);
        }


        //public ActionResult SeleccionProveedor() {
        //    ViewBag.Proveedores = new SelectList(db.Proveedors, "idProveedor", "Nombre");
        //    return View();
        //}


        //[HttpPost]
        //public ActionResult SeleccionProveedor()
        //{
            
        //    return View();
        //}

        //
        // GET: /Pago/Create

        public ActionResult Create(String idProveedor)
        {
            ViewBag.idFormaDePago = new SelectList(db.FormaDePagoes, "idFormaDePago", "descripcion");
            //var listaDeudas= from x in db.Deudas where x.idProveedor=Convert.ToInt32(idProveedor);
            ViewBag.deudas = new SelectList(db.Proveedors, "idProveedor", "Nombre");
            return View();
        }

        //
        // POST: /Pago/Create



        [HttpPost]
        public ActionResult Create(Pago pago)
        {
            if (ModelState.IsValid)
            {
                db.Pagoes.Add(pago);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idFormaDePago = new SelectList(db.FormaDePagoes, "idFormaDePago", "descripcion", pago.idFormaDePago);
            return View(pago);
        }

        //
        // GET: /Pago/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Pago pago = db.Pagoes.Find(id);
            if (pago == null)
            {
                return HttpNotFound();
            }
            ViewBag.idFormaDePago = new SelectList(db.FormaDePagoes, "idFormaDePago", "descripcion", pago.idFormaDePago);
            return View(pago);
        }

        //
        // POST: /Pago/Edit/5

        [HttpPost]
        public ActionResult Edit(Pago pago)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pago).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idFormaDePago = new SelectList(db.FormaDePagoes, "idFormaDePago", "descripcion", pago.idFormaDePago);
            return View(pago);
        }

        //
        // GET: /Pago/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Pago pago = db.Pagoes.Find(id);
            if (pago == null)
            {
                return HttpNotFound();
            }
            return View(pago);
        }

        //
        // POST: /Pago/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Pago pago = db.Pagoes.Find(id);
            db.Pagoes.Remove(pago);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Controllers/TipoDocController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CuentasPorPagar.Models;

namespace CuentasPorPagar.Controllers
{
    public class TipoDocController : Controller
    {
        private UsersContext db = new UsersContext();

        //
        // GET: /TipoDoc/

        public ActionResult Index()
        {
            return View(db.tipoDocumentoes.ToList());
        }

        //
        // GET: /TipoDoc/Details/5

        public ActionResult Details(int id = 0)
        {
            tipoDocumento tipodocumento = db.tipoDocumentoes.Find(id);
            if (tipodocumento == null)
            {
                return HttpNotFound();
            }
            return View(tipodocumento);
        }

        //
        // GET: /TipoDoc/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TipoDoc/Create

        [HttpPost]
        public ActionResult Create(tipoDocumento tipodocumento)
        {
            if (ModelState.IsValid)
            {
                db.tipoDocumentoes.Add(tipodocumento);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipodocumento);
        }

        //
        // GET: /TipoDoc/Edit/5

        public ActionResult Edit(int id = 0)
        {
            tipoDocumento tipodocumento = db.tipoDocumentoes.Find(id);
            if (tipodocumento == null)
            {
                return HttpNotFound();
            }
            return View(tipodocumento);
        }

        //
        // POST: /TipoDoc/Edit/5

        [HttpPost]
        public ActionResult Edit(tipoDocumento tipodocumento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipodocumento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipodocumento);
        }

        //
        // GET: /TipoDoc/Delete/5

        public ActionResult Delete(int id = 0)
        {
            tipoDocumento tipodocumento = db.tipoDocumentoes.Find(id);
            if (tipodocumento == null)
            {
                return HttpNotFound();
            }
            return View(tipodocumento);
        }

        //
        // POST: /TipoDoc/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            tipoDocumento tipodocumento = db.tipoDocumentoes.Find(id);
            db.tipoDocumentoes.Remove(tipodocumento);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Grupo No 2 Cuentas por Pagar/Fase IV Construccion/CuentasPorPagar/CuentasPorPagar/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es">
    <head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Scripts.Render("~/bundles/modernizr")
        @Styles.Render("~/Content/css")
        @Styles.Render("~/Content/themes/base/css")
        @Scripts.Render("~/bundles/jquery");
        @Scripts.Render("~/bundles/jqueryui")
     
           <style>
      body {
        padding-top: 50px; 
              }
    </style>
        <script>
            $(function () {
                //var x = $("input[type='datetime']");
                var x = $("#fechaFin");
                x.datepicker();
            });
        </script>

    </head>
    <body>
        <header>
        
         <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="@Url.Action("Index","Home")">Cuentas Por Pagar</a>
          <div class="nav-collapse collapse">
            <ul class="nav">

                            <li class="dropdown">
		                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Movimientos<b class="caret"></b></a>
		                        <ul class="dropdown-menu">
		                          <li><a href="@Url.Action("Create","Deuda")">Nueva Deuda</a></li>
		                          <li><a href="@Url.Action("Create","Pago")">Nuevo Pago</a></li>
		                          <li><a href="#">Accion3</a></li>
		                        </ul>
		                      </li>

                             <li class="dropdown">
		                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Proveedores<b class="caret"></b></a>
		                        <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Index","Proveedor")">Ver todos</a></li>
		                          <li><a href="@Url.Action("Create","Proveedor")">Crear</a></li>

		                        </ul>
		                      </li>


                          <li class="dropdown">
		                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Reportes<b class="caret"></b></a>
		                        <ul class="dropdown-menu">
		                          <li><a href="#">Accion1</a></li>
		                          <li><a href="#">Accion2</a></li>
		                          <li><a href="#">Accion3</a></li>
		                        </ul>
		                      </li>


                
                          <li class="dropdown">
		                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Otros Catalogos<b class="caret"></b></a>
		                        <ul class="dropdown-menu">
                                    <li><a href="@Url.Action("Index","TipoDoc")">Tipos de Documentos</a></li>
                                     <li><a href="@Url.Action("Index","FormaPago")">Formas de Pago</a></li>
		                        </ul>
		                      </li>
               

            </ul>
               @Html.Partial("_LoginPartial")
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    </header>

    <div class="container">
        @if(IsSectionDefined("featured")){
        <div class="hero-unit">
            @RenderSection("featured", required: false)
        </div>
        }

          @RenderBody()
      

    </div> 

     
@*         @Scripts.Render("~/bundles/jquery")   *@
         @Scripts.Render("~/Scripts/Bootstrap")

        @RenderSection("scripts", required: false)
         
        
       
       
    </body>
</html>